version: '2'
services:
  accounts:
    build: .
    restart: always
    container_name: accounts
    ports:
      - 1389:1389
    volumes:
      - ./config.coffee:/usr/src/app/config.coffee
    external_links:
      - mongodb
networks:
  default:
    external:
      name: service
